/**
 * Dummy feed items used when the real feed is empty.
 * Covers every content type: text, photo, video, audio, poem, document.
 * Media URLs point to freely-hosted samples — no auth required.
 */

import type { Post, Profile } from './supabase'

// ── Dummy author profiles ────────────────────────────────────────────────────

const DUMMY_AUTHORS: Profile[] = [
  {
    id: 'dummy-author-1',
    username: 'sophiachen',
    full_name: 'Sophia Chen',
    bio: 'Portrait & fine-art photographer based in Tokyo.',
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    website: '',
    profession: 'photography',
    professions: ['photography'],
    role_title: 'Fine Art Photographer',
    workplace: null,
    is_pro: true,
    personal_profile_public: true,
    follower_count: 2840,
    following_count: 412,
    friend_count: 38,
    post_count: 94,
    interests: [],
    post_formats: [],
    verification_count: 12,
    created_at: '2023-06-01T00:00:00Z',
  },
  {
    id: 'dummy-author-2',
    username: 'marcusbell',
    full_name: 'Marcus Bell',
    bio: 'Jazz musician & composer. Recording new album — out this winter.',
    avatar_url: 'https://i.pravatar.cc/150?img=12',
    website: '',
    profession: 'music',
    professions: ['music'],
    role_title: 'Jazz Musician',
    workplace: null,
    is_pro: true,
    personal_profile_public: true,
    follower_count: 1530,
    following_count: 280,
    friend_count: 21,
    post_count: 57,
    interests: [],
    post_formats: [],
    verification_count: 7,
    created_at: '2023-09-15T00:00:00Z',
  },
  {
    id: 'dummy-author-3',
    username: 'elenarossi',
    full_name: 'Elena Rossi',
    bio: 'Independent filmmaker — short films & documentaries.',
    avatar_url: 'https://i.pravatar.cc/150?img=20',
    website: '',
    profession: 'film',
    professions: ['film'],
    role_title: 'Filmmaker',
    workplace: null,
    is_pro: true,
    personal_profile_public: true,
    follower_count: 4120,
    following_count: 310,
    friend_count: 44,
    post_count: 133,
    interests: [],
    post_formats: [],
    verification_count: 18,
    created_at: '2022-11-03T00:00:00Z',
  },
  {
    id: 'dummy-author-4',
    username: 'arjunpoet',
    full_name: 'Arjun Mehta',
    bio: 'Words are my medium. Writing at the intersection of love and loss.',
    avatar_url: 'https://i.pravatar.cc/150?img=33',
    website: '',
    profession: 'writing',
    professions: ['writing'],
    role_title: 'Poet & Writer',
    workplace: null,
    is_pro: true,
    personal_profile_public: true,
    follower_count: 890,
    following_count: 155,
    friend_count: 17,
    post_count: 48,
    interests: [],
    post_formats: [],
    verification_count: 5,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'dummy-author-5',
    username: 'zoe.builds',
    full_name: 'Zoe Nakamura',
    bio: 'Software engineer turned indie game dev. Building in public.',
    avatar_url: 'https://i.pravatar.cc/150?img=9',
    website: '',
    profession: 'technology',
    professions: ['technology'],
    role_title: 'Indie Developer',
    workplace: null,
    is_pro: false,
    personal_profile_public: true,
    follower_count: 620,
    following_count: 198,
    friend_count: 29,
    post_count: 31,
    interests: [],
    post_formats: [],
    verification_count: 2,
    created_at: '2024-03-08T00:00:00Z',
  },
  {
    id: 'dummy-author-6',
    username: 'chefkarimi',
    full_name: 'Reza Karimi',
    bio: 'Michelin-trained chef · Persian & modern fusion cuisine.',
    avatar_url: 'https://i.pravatar.cc/150?img=58',
    website: '',
    profession: 'culinary',
    professions: ['culinary'],
    role_title: 'Executive Chef',
    workplace: 'Studio Karimi',
    is_pro: true,
    personal_profile_public: true,
    follower_count: 7340,
    following_count: 90,
    friend_count: 12,
    post_count: 220,
    interests: [],
    post_formats: [],
    verification_count: 31,
    created_at: '2022-04-17T00:00:00Z',
  },
]

// ── Helper to produce a "created_at" N hours ago ─────────────────────────────
function hoursAgo(h: number) {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
}

// ── Dummy Posts — one per content type ───────────────────────────────────────

export const DUMMY_POSTS: Post[] = [
  // 1. PHOTO — Pro Post ────────────────────────────────────────────────────────
  {
    id: 'dummy-post-photo',
    user_id: 'dummy-author-1',
    content_type: 'photo',
    caption: 'Golden hour over the rooftops of Shinjuku. Chased this light for three evenings. Worth every minute. #photography #tokyo #goldenHour',
    poem_text: '',
    media_url: 'https://picsum.photos/seed/oc-photo/900/600',
    thumb_url: 'https://picsum.photos/seed/oc-photo/600/400',
    display_url: 'https://picsum.photos/seed/oc-photo/900/600',
    media_path: '',
    tags: ['#photography', '#tokyo', '#goldenHour'],
    like_count: 312,
    comment_count: 24,
    share_count: 18,
    pro_upvote_count: 41,
    is_pro_post: true,
    post_type: 'pro',
    persona_discipline: 'photography',
    visibility: 'public',
    group_id: null,
    created_at: hoursAgo(3),
    expires_at: null,
    profiles: DUMMY_AUTHORS[0],
    user_liked: false,
    is_pro: false,
    user_pro_upvoted: false,
  },

  // 2. AUDIO — Pro Post ────────────────────────────────────────────────────────
  {
    id: 'dummy-post-audio',
    user_id: 'dummy-author-2',
    content_type: 'audio',
    caption: 'First excerpt from the new album — a slow-burn jazz waltz inspired by late-night drives. Rough mix, but the soul is there. #jazz #original #musician',
    poem_text: '',
    media_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    thumb_url: '',
    display_url: '',
    media_path: '',
    tags: ['#jazz', '#original', '#musician'],
    like_count: 189,
    comment_count: 31,
    share_count: 12,
    pro_upvote_count: 28,
    is_pro_post: true,
    post_type: 'pro',
    persona_discipline: 'music',
    visibility: 'public',
    group_id: null,
    created_at: hoursAgo(7),
    expires_at: null,
    profiles: DUMMY_AUTHORS[1],
    user_liked: false,
    is_pro: false,
    user_pro_upvoted: false,
  },

  // 3. VIDEO — Pro Post ────────────────────────────────────────────────────────
  {
    id: 'dummy-post-video',
    user_id: 'dummy-author-2',
    content_type: 'video',
    caption: 'Behind the scenes from the short film we wrapped last week. Shot entirely on a single anamorphic prime in the old quarter. #filmmaking #BTS #cinematography',
    poem_text: '',
    media_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumb_url: 'https://picsum.photos/seed/oc-video/900/500',
    display_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    media_path: '',
    tags: ['#filmmaking', '#BTS', '#cinematography'],
    like_count: 540,
    comment_count: 47,
    share_count: 63,
    pro_upvote_count: 87,
    is_pro_post: true,
    post_type: 'pro',
    persona_discipline: 'film',
    visibility: 'public',
    group_id: null,
    created_at: hoursAgo(14),
    expires_at: null,
    profiles: DUMMY_AUTHORS[2],
    user_liked: false,
    is_pro: false,
    user_pro_upvoted: false,
  },

  // 4. TEXT — General Post ─────────────────────────────────────────────────────
  {
    id: 'dummy-post-text',
    user_id: 'dummy-author-4',
    content_type: 'text',
    caption: "Shipped my first open-source library today after six months of nights and weekends. 47 stars in the first hour. Honestly didn't expect that. Keep shipping. #buildinpublic #technology #openSource",
    poem_text: '',
    media_url: '',
    thumb_url: '',
    display_url: '',
    media_path: '',
    tags: ['#buildinpublic', '#technology', '#openSource'],
    like_count: 94,
    comment_count: 16,
    share_count: 8,
    pro_upvote_count: 0,
    is_pro_post: false,
    post_type: 'general',
    persona_discipline: 'technology',
    visibility: 'public',
    group_id: null,
    created_at: hoursAgo(5),
    expires_at: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
    profiles: DUMMY_AUTHORS[4],
    user_liked: false,
    is_pro: false,
    user_pro_upvoted: false,
  },

  // 5. POEM — Pro Post ─────────────────────────────────────────────────────────
  {
    id: 'dummy-post-poem',
    user_id: 'dummy-author-3',
    content_type: 'poem',
    caption: 'Something I wrote on a sleepless Tuesday. #poetry #writing',
    poem_text: `We carry the weight of unsent letters,
folded in the chest
like old maps of cities
we never had the courage to visit.

The heart is a slow traveller —
it arrives long after the body has moved on,
still clutching the name
of someone who has already changed their address.`,
    media_url: '',
    thumb_url: '',
    display_url: '',
    media_path: '',
    tags: ['#poetry', '#writing'],
    like_count: 271,
    comment_count: 38,
    share_count: 55,
    pro_upvote_count: 62,
    is_pro_post: true,
    post_type: 'pro',
    persona_discipline: 'writing',
    visibility: 'public',
    group_id: null,
    created_at: hoursAgo(20),
    expires_at: null,
    profiles: DUMMY_AUTHORS[3],
    user_liked: false,
    is_pro: false,
    user_pro_upvoted: false,
  },

  // 6. DOCUMENT — Pro Post ─────────────────────────────────────────────────────
  {
    id: 'dummy-post-document',
    user_id: 'dummy-author-5',
    content_type: 'document',
    caption: 'Published my recipe development methodology — how I test and iterate on flavour profiles before a dish goes on the menu. Free to read. #culinary #chefLife #methodology',
    poem_text: '',
    media_url: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF2.pdf',
    thumb_url: '',
    display_url: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF2.pdf',
    media_path: '',
    tags: ['#culinary', '#chefLife', '#methodology'],
    like_count: 143,
    comment_count: 22,
    share_count: 34,
    pro_upvote_count: 19,
    is_pro_post: true,
    post_type: 'pro',
    persona_discipline: 'culinary',
    visibility: 'public',
    group_id: null,
    created_at: hoursAgo(31),
    expires_at: null,
    profiles: DUMMY_AUTHORS[5],
    user_liked: false,
    is_pro: false,
    user_pro_upvoted: false,
  },
]

// ── Export as FeedItems ──────────────────────────────────────────────────────
// Interleave pro and general so the feed looks natural
export const DUMMY_FEED_ITEMS = DUMMY_POSTS.map(post => ({
  type: post.post_type === 'pro' ? ('pro_post' as const) : ('general_post' as const),
  post,
}))
